name: Generate Minor Version

on:
  workflow_dispatch:

jobs:
  generate_minor:
    name: arctouch/generate_minor
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v2

      - name: Run script ğŸ–¼ï¸
        run: |
          npm install
          npm run minor