name: Generate Major Version

on:
  workflow_dispatch:

jobs:
  generate_major:
    name: arctouch/generate_major
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v2

      - name: Run script ğŸ–¼ï¸
        run: |
          npm install
          npm run major